source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GMEllipticCurveCrypto_Example', :exclusive => true do
  pod 'GMEllipticCurveCrypto', :path => '../'
end

target 'GMEllipticCurveCrypto_Tests', :exclusive => true do
  pod 'GMEllipticCurveCrypto', :path => '../'

  
end
